import { Calculator } from "./calc.js";

Calculator.add(2, 5);
Calculator.add(-1,3);
Calculator.add(2,-4);
Calculator.add(1, 0);
Calculator.add(0, 1);
Calculator.add('6', 0);
Calculator.add(1, 'test');
Calculator.add(NaN, 0);
Calculator.add(6, NaN);
Calculator.add(6, Infinity);
Calculator.add(Infinity, 2);
console.log(Calculator.calcHistory);
Calculator.sub(2, 5);
Calculator.sub(-1,3);
Calculator.sub(2,-4);
Calculator.sub(1, 0);
Calculator.sub(0, 1);
Calculator.sub('6', 0);
Calculator.sub(1, 'test');
Calculator.sub(NaN, 0);
Calculator.sub(6, NaN);
Calculator.sub(6, Infinity);
Calculator.sub(Infinity, 2);
console.log(Calculator.calcHistory);
Calculator.mul(2, 5);
Calculator.mul(-1,3);
Calculator.mul(2,-4);
Calculator.mul(1, 0);
Calculator.mul(0, 1);
Calculator.mul('6', 0);
Calculator.mul(1, 'test');
Calculator.mul(NaN, 0);
Calculator.mul(6, NaN);
Calculator.mul(6, Infinity);
Calculator.mul(Infinity, 2);
console.log(Calculator.calcHistory);
Calculator.div(2, 5);
Calculator.div(-1,3);
Calculator.div(2,-4);
Calculator.div(1, 0);
Calculator.div(0, 1);
Calculator.div('6', 0);
Calculator.div(1, 'test');
Calculator.div(NaN, 0);
Calculator.div(6, NaN);
Calculator.div(6, Infinity);
Calculator.div(Infinity, 2);
console.log(Calculator.calcHistory);